export const AUTH = {
  IS_READY:"IS_READY",
  SET_USER:"SET_USER",
  SET_LOADING:"SET_LOADING"
};

export const USER = {
  SET_NICKNAME:"SET_NICKNAME",

  UPDATE_USERINFOR:"UPDATE_USERINFOR",

  RESET_UPLOAD_AVATAR_STATUS:"RESET_UPLOAD_AVATAR_STATUS",
  UPLOAD_AVATAR:"UPLOAD_AVATAR",
  UPLOAD_AVATAR_SUCCESS:"UPLOAD_AVATAR_SUCCESS",
  UPLOAD_AVATAR_FAILED:"UPLOAD_AVATAR_FAILED",

  UPLOAD_THUMBNAIL:"UPLOAD_THUMBNAIL",
  UPLOAD_THUMBNAIL_SUCCESS:"UPLOAD_THUMBNAIL_SUCCESS",
  UPLOAD_THUMBNAIL_FAILED:"UPLOAD_THUMBNAIL_FAILED",

  SET_USERINFOR:"SET_USERINFOR",
  SET_USERINFOR_SERVER:"SET_USERINFOR_SERVER",

  SYNC_USERINFOR:"SYNC_USERINFOR",
  SYNC_USERINFOR_SUCCESS:"SYNC_USERINFOR_SUCCESS",
  SYNC_USERINFOR_FAILED:"SYNC_USERINFOR_FAILED",

  GET_ALL_USER:'GET_ALL_USER',
  GET_ALL_USER_SUCCESS:'GET_ALL_USER_SUCCESS',
  GET_ALL_USER_FAILED:'GET_ALL_USER_FAILED',
};


export const POST = {
  RESET_UPLOAD_POST_STATUS:"RESET_UPLOAD_POST_STATUS",
  UPLOAD_POST:"UPLOAD_POST",
  UPLOAD_POST_SUCCESS:"UPLOAD_POST_SUCCESS",
  UPLOAD_POST_FAILED:"UPLOAD_POST_FAILED",

  GET_POST_BY_LOCATION:"GET_POST_BY_LOCATION",
  GET_POST_BY_LOCATION_VALUE:"GET_POST_BY_LOCATION_VALUE",
};

export const CONTROL_APP = {
  UPDATE_DRAWER: "UPDATE_DRAWER",
  SET_BACKGROUND_SCREEN:"SET_BACKGROUND_SCREEN",

  CHANGE_CONNECTED:'CHANGE_CONNECTED',

  INIT_APP:'INIT_APP',
  UPDATE_SETTING: "UPDATE_SETTING",
};
